#!/bin/sh

FILE_NAME="$(dirname "$0")/_/husky.sh"

# Conditionally invoke so as to avoid running pnpm commands if this is a clean checkout (ie before installing pnpm modules)
if [ -f $FILE_NAME ]; then
  . $FILE_NAME
  pnpm run prepare-code
fi
